excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - SwiftLintDemo/AppDelegate.swift
  - SwiftLintDemoTests
  - SwiftLintDemoUITests

disabled_rules:
  - trailing_whitespace

opt_in_rules: # some rules are only opt-in
  - empty_count

custom_rules:
  id_suffix_naming:
    name: "Wrong name"
    regex: "(ID)"
    match_kinds:
      - comment
      - identifier
    message: "Use 'Id' instead 'ID'"
    severity: error
